# Generated by Django 2.2 on 2019-04-19 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refugee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=250, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=250, verbose_name='Last Name')),
                ('gender', models.CharField(max_length=100, verbose_name='Gender')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Age')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Phone Number')),
                ('demographic_info', models.CharField(max_length=250, verbose_name='Demographic Info')),
                ('ethinicity', models.CharField(max_length=250, verbose_name='Ethinicity')),
                ('street_number', models.CharField(max_length=30, verbose_name='Street Number')),
                ('street_name', models.CharField(max_length=150, verbose_name='Street Name')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('zip_code', models.CharField(max_length=10, verbose_name='ZIP Code')),
                ('martial_status', models.CharField(choices=[('single', 'Single'), ('married', 'MARRIED')], default='single', max_length=9)),
            ],
        ),
    ]
