# Generated by Django 2.2 on 2019-05-07 20:54

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time Created')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Refugee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Last Name')),
                ('gender', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gender')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Age')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number')),
                ('demographic_info', models.CharField(blank=True, max_length=250, null=True, verbose_name='Demographic Info')),
                ('ethnicity', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ethinicity')),
                ('street_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Street Number')),
                ('street_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Street Name')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='ZIP Code')),
                ('emergency_contact', models.CharField(blank=True, max_length=300, null=True, verbose_name='Emergency Contact')),
                ('martial_status', models.CharField(choices=[('single', 'Single'), ('married', 'MARRIED')], default='single', max_length=9)),
            ],
            options={
                'verbose_name': 'Refugee',
                'verbose_name_plural': 'Refugees',
            },
        ),
        migrations.CreateModel(
            name='CallMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time Created')),
                ('duration', models.FloatField(verbose_name='Duration in seconds')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('audio', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Audio')),
                ('category', models.ManyToManyField(to='speakez_core.Category')),
            ],
            options={
                'verbose_name': 'Call Message',
                'verbose_name_plural': 'Call Messages',
            },
        ),
    ]
