# Generated by Django 2.2 on 2019-11-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakez_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callmessage',
            name='date_time_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Date and Time Edited'),
        ),
        migrations.AddField(
            model_name='callmessage',
            name='deleted',
            field=models.BooleanField(default=0, verbose_name='Deleted'),
        ),
    ]
