# Generated by Django 2.2 on 2019-04-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakez_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refugee',
            name='ethinicity',
        ),
        migrations.AddField(
            model_name='refugee',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ethinicity'),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='demographic_info',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Demographic Info'),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='street_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Street Name'),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='street_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Street Number'),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ZIP Code'),
        ),
    ]
