# Generated by Django 2.2 on 2019-05-22 19:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('speakez_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_id', models.CharField(max_length=250, verbose_name='caller id')),
                ('admin_username', models.CharField(max_length=250, verbose_name='caller username')),
                ('date_time_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time Created')),
                ('message_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speakez_core.CallMessage')),
            ],
            options={
                'verbose_name': 'Call Log',
                'verbose_name_plural': 'Call Logs',
            },
        ),
        migrations.CreateModel(
            name='CallLogDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speakez_core.CallLog')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speakez_core.Refugee')),
            ],
            options={
                'verbose_name': 'Call Log Detail',
                'verbose_name_plural': 'Call Log Details',
            },
        ),
    ]
