# Generated by Django 2.2 on 2019-05-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakez_core', '0002_calllog_calllogdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllogdetail',
            name='call_sid',
            field=models.CharField(default=11111111111111111111111111, max_length=34, verbose_name='twilio call sid'),
            preserve_default=False,
        ),
    ]
