# Generated by Django 2.2 on 2019-05-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakez_core', '0002_auto_20190419_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refugee',
            options={'verbose_name': 'Refugee', 'verbose_name_plural': 'Refugees'},
        ),
        migrations.AddField(
            model_name='refugee',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Emergency Contact'),
        ),
    ]
