# Generated by Django 2.2 on 2019-05-16 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakez_core', '0002_auto_20190515_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav'])], verbose_name='Audio'),
        ),
    ]
