# Generated by Django 2.2 on 2019-11-06 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('speakez_core', '0002_auto_20191102_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugee',
            name='date_time_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time Created'),
        ),
        migrations.AddField(
            model_name='refugee',
            name='date_time_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Date and Time Edited'),
        ),
        migrations.AddField(
            model_name='refugee',
            name='deleted',
            field=models.BooleanField(default=0, verbose_name='Deleted'),
        ),
    ]
