# Generated by Django 2.2 on 2019-06-07 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speakez_core', '0003_calllogdetail_call_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callmessage',
            name='category',
        ),
        migrations.AddField(
            model_name='callmessage',
            name='category',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='speakez_core.Category'),
            preserve_default=False,
        ),
    ]
