# Generated by Django 2.2 on 2019-05-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakez_core', '0003_auto_20190502_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugee',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Emergency Contact'),
        ),
    ]
