# Generated by Django 2.2 on 2019-11-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakez_core', '0003_auto_20191106_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugee',
            name='first_name',
            field=models.CharField(blank=True, default='jim', max_length=250, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='refugee',
            name='last_name',
            field=models.CharField(blank=True, default='yi', max_length=250, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
